### ISSUE TITLE
Remaining components to be ported

### ISSUE THREAD

**Issue by wc-matteo** [dimik/react-material-web-components#1]
What's missing from [these](http://material-components-web.appspot.com/)?

At first glance, mainly the *slider*...

Is the lib production ready? Are all the components currently present implemented fully?

Thanks

**Comment by dimik** [comment]
Hi @wc-matteo, thank you for your interest!
As far as i know original MDC is not production ready yet – all components have major version less than "1". We have a plan to use this library for production soon.

But need to notice that it uses [simple approach](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md#the-simple-approach-wrapping-mdc-web-vanilla-components)  means working with original Foundation and Adapters classes from MDC.

Adding a slider is not a big issue, all other components are implemented so far.

**Comment by wc-matteo** [comment]
Thank you for the prompt reply.

> But need to notice that it uses simple approach means working with original Foundation and Adapters classes from MDC.

Ah, interesting... I didn't know you could do that. I thought you had to write new Adapters.
Does the simple approach have any drawbacks / shortcomings in react (web)?

**Comment by dimik** [comment]
I didn't notice any drawback but there are some specific peculiarities when component is updating. The original google adapters are very well written and tested. Currently we don't have any sufficient resources for that

**Comment by wc-matteo** [comment]
Thanks.
