### ISSUE TITLE
Button's ripple effect not present

### ISSUE THREAD

**Issue by wc-matteo** [dimik/react-material-web-components#2]
I've included a Button like this:

`import {Button} from 'react-material-web-components'`

And I'm using this for the styles:

`import 'material-components-web/dist/material-components-web.css'`

The button works:

![image](https://user-images.githubusercontent.com/10562635/28159452-43b842ae-67bd-11e7-9c8a-97ac9f8fdf40.png)

But has not ripple effect...

**Or more correctly, the ripple is the "fake" css ripple.**

**Comment by wc-matteo** [comment]
By the way, what would you suggest is the best way to include the styles?

**Comment by wc-matteo** [comment]
Now I see that in the example page they attach it manually:

```js
// Because we load our CSS via webpack, we need to ensure that all of the correct styles
// are applied before ripples are attached. Otherwise, ripples may use the computed styles of
// elements before our CSS is applied, leading to improper UX.
(function() {
var pollId = 0;
pollId = setInterval(function() {
    var pos = getComputedStyle(document.querySelector('.mdc-button')).position;
    if (pos === 'relative') {
    init();
    clearInterval(pollId);
    }
}, 250);
function init() {
    var btns = document.querySelectorAll('.mdc-button:not([data-demo-no-js])');
    for (var i = 0, btn; btn = btns[i]; i++) {
    mdc.ripple.MDCRipple.attachTo(btn);
    }
}
})();
```

**Comment by dimik** [comment]
Thank you to reported that.
Fix has been landed with version 2.0.14 

```html
 <Button
  accent
  ripple
>bla</Button>
```

**Comment by dimik** [comment]
We are using scss files from material-components-web builded with webpack

**Comment by wc-matteo** [comment]
Holy shit that was fast! :D
